-- Created 09/10/20
-- Purpose: To provide the contract manager email address based on the inputted resource ID  
Select distinct C.CONTRACTMANAGEREMAIL, C.CONTRACTID, CP.SCECONTRACTMANAGER
from 
EMDM.EBX_DB_CNTRCT_RSRC_MTR_MAP_V  RM 
JOIN EMDM.EBX_DB_CONTRACT_EFFECTIVE_V C ON RM.CONTRACTID = C.CONTRACTID
Left JOIN EMDM.EBX_DB_COUNTER_PARTIES CP ON C.EXTERNALPARTYID_ = CP.PARTYID
Where 
RM.ISORESOURCEID = 'ETIWND_2_SOLAR2' and 
sysdate between RM.RECORDEFFECTIVEDATE_STARTDATE and RM.RECORDEFFECTIVEDATE_ENDDATE


 


